version: '3.8'

services:
  frontend:
    build:
      context: ./domce-front 
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_MAPS_API: ${VITE_GOOGLE_MAPS_API}
    image: ${DOCKER_USERNAME}/domce-frontend:latest
    ports:
      - "80:80" 
    environment:
      - VITE_GOOGLE_MAPS_API=${VITE_GOOGLE_MAPS_API}
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/domce-backend:latest"
    ports:
      - "4000:4000" 
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
